deployment:
  image: seccomch/wep-media-light:latest
  imagePullPolicy: Always
  imagePullSecret:
  env:
    TOKEN: x3qYBvmWqxVJd6wA9BZ8baiDbYZD
    DEBUG: 'false'
    NUM_CLUSTERS: '1'
  replicaCount: 1

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    host: media-reatch.wepublish.media
    path: /

  pvc:
    enabled: true
    storage: 20Gi

  labels: { }
