version: '3.7'
services:
  media:
    build:
      context: .
      target: app
    ports:
      - 4100:4100
      - 4109:4109
    environment:
      NUM_CLUSTERS: 1
      STORAGE_PATH: ./.media
      TOKEN: secret
    volumes:
      - "./src:/home/node/src"
      - "./.media:/home/node/.media"
